test compare and download coverage

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -26,38 +26,45 @@ jobs:
           cd backend
           npm ci
 
-      - name: Download previous coverage report
-        uses: actions/download-artifact@v4 
-        with:
-          name: code-coverage-report
-          github-token: ${{ secrets.GITHUB_TOKEN }} 
+      # - name: Download previous coverage report
+      #   uses: actions/download-artifact@v4 
+      #   with:
+      #     name: code-coverage-report
+      #     github-token: ${{ secrets.GITHUB_TOKEN }} 
 
 
-      - name: Display structure of downloaded files 
-        run: ls -R
+      # - name: Display structure of downloaded files 
+      #   run: ls -R
 
-      - shell: bash
-        run: |
-          value=`cat index.html`
-          PREVIOUS_COVERAGE=$(echo $value | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
-          echo "Previous Coverage: $PREVIOUS_COVERAGE"
-          echo "$PREVIOUS_COVERAGE" > $GITHUB_OUTPUT
-        id: previous_coverage
+      # - shell: bash
+      #   run: |
+      #     value=`cat index.html`
+      #     PREVIOUS_COVERAGE=$(echo $value | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
+      #     echo "Previous Coverage: $PREVIOUS_COVERAGE"
+      #     echo "$PREVIOUS_COVERAGE" > $GITHUB_OUTPUT
+      #   id: previous_coverage
 
       - name: Run tests
         run: |
           cd backend
           npm run test
       
-          COVERAGE_PERCENTAGE=$(cat coverage/index.html | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
-          echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
-          PREVIOUS_COVERAGE=$(cat ${{ steps.previous_coverage.outputs.GITHUB_OUTPUT }})
+          # COVERAGE_PERCENTAGE=$(cat coverage/index.html | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
+          # echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
+          # PREVIOUS_COVERAGE=$(cat ${{ steps.previous_coverage.outputs.GITHUB_OUTPUT }})
 
 
-          if (( $(echo "$COVERAGE_PERCENTAGE < $PREVIOUS_COVERAGE" | bc -l) )); then
-            echo "Coverage is less than previous coverage: $PREVIOUS_COVERAGE%"
-            exit 1  # Fail the job
-          fi
+          # if (( $(echo "$COVERAGE_PERCENTAGE < $PREVIOUS_COVERAGE" | bc -l) )); then
+          #   echo "Coverage is less than previous coverage: $PREVIOUS_COVERAGE%"
+          #   exit 1  # Fail the job
+          # fi
+
+      - name: Coverage Diff
+        uses: GreatWizard/coverage-diff-action@v1.0.8
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          coverage-filename: backend/coverage/coverage-final.json
+
 
       - name: Archive code coverage results
         uses: actions/upload-artifact@v4
