test github action workflow

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -26,11 +26,38 @@ jobs:
           cd backend
           npm ci
 
+      - name: Download previous coverage report
+        uses: actions/download-artifact@v4  
+        with:
+          name: code-coverage-report
+      - shell: bash
+        run: |
+          value=`cat index.html`
+          PREVIOUS_COVERAGE=$(echo $value | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
+          echo "Previous Coverage: $PREVIOUS_COVERAGE"
+          echo "$PREVIOUS_COVERAGE" > $GITHUB_OUTPUT
+        id: previous_coverage
+
       - name: Run tests
         run: |
           cd backend
           npm run test
-        # job fail if coverage rate less than 60%
+      
+          COVERAGE_PERCENTAGE=$(cat coverage/index.html | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
+          echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
+          PREVIOUS_COVERAGE=$(cat ${{ steps.previous_coverage.outputs.GITHUB_OUTPUT }})
+
+
+          if (( $(echo "$COVERAGE_PERCENTAGE < $PREVIOUS_COVERAGE" | bc -l) )); then
+            echo "Coverage is less than previous coverage: $PREVIOUS_COVERAGE%"
+            exit 1  # Fail the job
+          fi
+
+      - name: Archive code coverage results
+        uses: actions/upload-artifact@v4
+        with:
+          name: code-coverage-report
+          path: backend/coverage/index.html
       
       # - name: Install dependencies
       #   run: |
@@ -45,10 +72,18 @@ jobs:
       - name: Build and push Docker image
         run: |
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+
           docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:${{ github.run_id }} ./frontend
+          docker tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:${{ github.run_id }} ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:latest
+
           docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.run_id }} ./backend
+          docker tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.run_id }} ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:latest
+          
           docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:${{ github.run_id }}
+          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:latest
+          
           docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.run_id }}
+          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:latest
 
   deploy-k8s:
     needs: build-test-deploy-docker
@@ -75,17 +110,13 @@ jobs:
             ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.run_id }}
             ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:${{ github.run_id }}
           skip-tls-verify: true
-    
-      # - name: update the deployment
-      #   run: |
-      #     kubectl set image deployment/todo-app-deploy todo-app-container=ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.run_id }}
-      #     kubectl set image deployment/todo-ui-deploy todo-ui-container=ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:${{ github.run_id }}
 
     # Check k8s deployment status and return status
       - name: Check deployment status
         run: |
           kubectl rollout status deployment/todo-app-deploy
-          kubectl rollout status deployment/todo-ui-deploy 
+          kubectl rollout status deployment/todo-ui-deploy
+          kubectl get deployments -o wide
 
 
 
